name: Build and Package

on:
  pull_request:
    branches: [ master ]

env:
  SOLUTION_NAME: Atlassian.Stash.sln
  UNIT_TEST_PROJECT_PATH: ./test/Atlassian.Stash.UnitTests/
  BUILD_OUTPUT_PATH: ./buildOutput

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Determine change type
      id: bump
      uses: zwaldowski/match-label-action@v2
      with:
        allowed: major,minor,patch

    - name: Set version
      id: next_version
      uses: zwaldowski/semver-release-action@v2
      with:
        dry_run: true
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "${{ steps.next_version.outputs.version }}"

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore --output ./buildOutput "/p:Version=${{ steps.next_version.outputs.version }}"

    - name: Run unit tests
      run: dotnet test ${{ env.UNIT_TEST_PROJECT_PATH }} --no-restore --verbosity normal

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: generated-nuget-packages
        path: |
          ${{ env.BUILD_OUTPUT_PATH }}/*.nupkg
          ${{ env.BUILD_OUTPUT_PATH }}/*.snupkg
